name: PYPI Publishing

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/py-logic
    permissions:
      id-token: write
    steps:
    - name: Install dependencies
      run: pip install --upgrade build

    - name: Build package
      run: pwd && ls -la && cd .. && python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
